name: Test and Publish CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: "Build and test"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci --prefix test/
      - run: npm run build
      - run: npm test

  publish:
    name: "Publish"
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - run: npm run build
      - name: "Publish if version changes"
        uses: JS-DevTools/npm-publish@v2.2.0
        with:
          token: ${{ secrets.NPM_TOKEN }}

